### PR TITLE
Updating Defs

### PR DESCRIPTION
**Pull request by ChronoFinale**
quality of life functions for finding potions or any other items that have charges

### CODE REVIEW

**Comment by TheTS** [comment]
IMO the original should just be written this way, because then the scripter could just enter the exact name (which they currently do) or enter a sub-string (the purpose of this). This way you can avoid adding bloat functions

**Comment by ChronoFinale** [comment]
I agree, kyle what do you think

**Comment by ChronoFinale** [comment]
For some reason I am having trouble getting some object's name even though the IDs are perfectly readable, 

Ex
did a get all inside NMZ and printed out the names and IDs of object around me
10784 Rock
1460 
26281 
10785 Rock
1460 
26290 
26282 
1459 
1460 
1460 
1460 
26284 
1460 
1460 
26283 
26285 
1460 
1460 
26287 
26286 
1459 
1460 
26289 
26288 
1459 
731 
1459 
731 
3609 
3609 
732 
1459 
731 
1459 
1460 
1460 
1460 
1460

**Comment by ChronoFinale** [comment]
So the issue is that when reading from the configuration files, it assumes that each line has the line number corresponding to the ID of the object npc or item. Since some of these items were removed from the cache, some of the items skip, maybe theres a better way besides just either keeping everything old in or putting empty lines

**Comment by KyleHunter** [comment]
You have to have it be exactly based on the line number, as any other way would be far to slow to grab it from.
Also, I don't like using Pos() for the name search as the nice part about reflection is the fact that you can search exact names, avoiding times where names overlap

**Comment by TheTS** [comment]
But the whole point of this was so you _don't_ have to avoid overlapping names. If you wanted to, you would just type the full name.

**Pull request closed without merging**
