### PR TITLE
World Selection Update and Stats Addition

### PR DESCRIPTION
**Pull request by ChronoFinale**
Added so the random world selector will not select a Deadman Mode by default
Added the stats lib from aerolib

### CODE REVIEW

**Comment by ChronoFinale** [comment]
Added fixed typo of 'wield' was 'weild'

**Comment by KyleHunter** [comment]
I would merge it excluding the stats. The stats don't match the includes delphi standards st all..

**Comment by KyleHunter** [comment]
Also, you don't even include the stats within the include. Add it to internals/includes iirc

**Comment by ChronoFinale** [comment]
Will fix this I copied it from aero lib, but will update it to match standards

**Comment by ChronoFinale** [comment]
Rebased and squashed to a single commit

**Pull request merged**
